"""Serverless Workflow SDK v1 - Python classes for Serverless Workflow DSL 1.0."""

# Base types and classes
# Authentication
from serverlessworkflow.sdk.authentication import (
    BasicAuthenticationConfiguration,
    BasicAuthenticationPolicy,
    BearerAuthenticationConfiguration,
    BearerAuthenticationPolicy,
    DigestAuthenticationConfiguration,
    DigestAuthenticationPolicy,
    OAuth2AuthenticationConfiguration,
    OAuth2AuthenticationPolicy,
    OAuth2Client,
    OAuth2Endpoints,
    OAuth2Token,
    OAuth2TokenRequest,
    OpenIdConnectAuthenticationPolicy,
    ReferenceableAuthenticationPolicy,
)
from serverlessworkflow.sdk.base import (
    Duration,
    Error,
    ErrorFilter,
    Export,
    ExternalResource,
    FlowDirective,
    Input,
    Output,
    RuntimeExpression,
    Schema,
    TaskBase,
    TaskItem,
    Timeout,
    UriTemplate,
)

# Call tasks
from serverlessworkflow.sdk.call_tasks import (
    AsyncApiInboundMessage,
    AsyncApiMessageConsumptionPolicy,
    AsyncApiOutboundMessage,
    AsyncApiServer,
    AsyncApiSubscription,
    CallA2AArguments,
    CallA2ATask,
    CallAsyncApiArguments,
    CallAsyncApiTask,
    CallFunctionTask,
    CallGrpcArguments,
    CallGrpcTask,
    CallHttpArguments,
    CallHttpTask,
    CallMcpArguments,
    CallMcpTask,
    CallOpenApiArguments,
    CallOpenApiTask,
    CallTask,
    GrpcService,
    McpClient,
    McpHttpTransport,
    McpStdioTransport,
    McpTransport,
    SubscriptionIterator,
)

# Endpoints
from serverlessworkflow.sdk.endpoint import (
    Catalog,
    Endpoint,
)

# Events
from serverlessworkflow.sdk.events import (
    Correlation,
    EventConsumptionStrategy,
    EventConsumptionStrategyAll,
    EventConsumptionStrategyAny,
    EventConsumptionStrategyOne,
    EventFilter,
    EventProperties,
)

# Retry policies
from serverlessworkflow.sdk.retry import (
    ConstantBackoff,
    ExponentialBackoff,
    LinearBackoff,
    RetryJitter,
    RetryLimit,
    RetryLimitAttempt,
    RetryPolicy,
)

# Tasks
from serverlessworkflow.sdk.tasks import (
    CatchConfiguration,
    ContainerConfiguration,
    ContainerLifetime,
    DoTask,
    EmitConfiguration,
    EmitEventConfiguration,
    EmitTask,
    ForConfiguration,
    ForkConfiguration,
    ForkTask,
    ForTask,
    ListenConfiguration,
    ListenTask,
    RaiseConfiguration,
    RaiseTask,
    RunConfiguration,
    RunTask,
    ScriptConfiguration,
    SetTask,
    ShellConfiguration,
    SwitchCase,
    SwitchTask,
    Task,
    TryTask,
    WaitTask,
    WorkflowConfiguration,
)

# Workflow
from serverlessworkflow.sdk.workflow import (
    Document,
    Extension,
    Schedule,
    Use,
    Workflow,
)

__all__ = [
    # Base
    "RuntimeExpression",
    "UriTemplate",
    "Duration",
    "ExternalResource",
    "Schema",
    "Input",
    "Output",
    "Export",
    "Timeout",
    "Error",
    "ErrorFilter",
    "FlowDirective",
    "TaskBase",
    "TaskItem",
    # Authentication
    "OAuth2Token",
    "OAuth2Client",
    "OAuth2TokenRequest",
    "OAuth2Endpoints",
    "BasicAuthenticationConfiguration",
    "BasicAuthenticationPolicy",
    "BearerAuthenticationConfiguration",
    "BearerAuthenticationPolicy",
    "DigestAuthenticationConfiguration",
    "DigestAuthenticationPolicy",
    "OAuth2AuthenticationConfiguration",
    "OAuth2AuthenticationPolicy",
    "OpenIdConnectAuthenticationPolicy",
    "ReferenceableAuthenticationPolicy",
    # Endpoints
    "Endpoint",
    "Catalog",
    # Events
    "EventProperties",
    "Correlation",
    "EventFilter",
    "EventConsumptionStrategyOne",
    "EventConsumptionStrategyAny",
    "EventConsumptionStrategyAll",
    "EventConsumptionStrategy",
    # Retry
    "ConstantBackoff",
    "ExponentialBackoff",
    "LinearBackoff",
    "RetryLimitAttempt",
    "RetryLimit",
    "RetryJitter",
    "RetryPolicy",
    # Call tasks
    "AsyncApiServer",
    "AsyncApiOutboundMessage",
    "AsyncApiInboundMessage",
    "SubscriptionIterator",
    "AsyncApiMessageConsumptionPolicy",
    "AsyncApiSubscription",
    "CallAsyncApiArguments",
    "CallAsyncApiTask",
    "GrpcService",
    "CallGrpcArguments",
    "CallGrpcTask",
    "CallHttpArguments",
    "CallHttpTask",
    "CallOpenApiArguments",
    "CallOpenApiTask",
    "CallA2AArguments",
    "CallA2ATask",
    "McpHttpTransport",
    "McpStdioTransport",
    "McpTransport",
    "McpClient",
    "CallMcpArguments",
    "CallMcpTask",
    "CallFunctionTask",
    "CallTask",
    # Tasks
    "DoTask",
    "ForkConfiguration",
    "ForkTask",
    "EmitEventConfiguration",
    "EmitConfiguration",
    "EmitTask",
    "ForConfiguration",
    "ForTask",
    "ListenConfiguration",
    "ListenTask",
    "RaiseConfiguration",
    "RaiseTask",
    "ContainerLifetime",
    "ContainerConfiguration",
    "ScriptConfiguration",
    "ShellConfiguration",
    "WorkflowConfiguration",
    "RunConfiguration",
    "RunTask",
    "SetTask",
    "SwitchCase",
    "SwitchTask",
    "CatchConfiguration",
    "TryTask",
    "WaitTask",
    "Task",
    # Workflow
    "Document",
    "Extension",
    "Use",
    "Schedule",
    "Workflow",
]

__version__ = "1.0.0"
